from fastapi import FastAPI
from pydantic import BaseModel
import joblib
from src.config import MODELS_DIR

# A FastAPI application with two endpoints GET/ and POST/classify
# GET/ exists entirely for a health check of the uvicorn server
# POST/classify - the actual endpoint that takes an SMS, runs it through the model, and returns spam/ham & confidence score
# The server lives on http://127.0.0.1:8000 - returns a healthcheck JSON (see @app.get("/"))
# To test:
# 1. Run: uvicorn src.api:app --reload to start uvicorn server
# 2. Go to: http://127.0.0.1:8000/docs - an interactive interface generated by FastAPI to test all endpoints
# 3. Head to /classify, press 'Try it out' and replace the string value with a message
# e.g. "Congratulations! You have won a free iPhone. Click here to claim your prize now!"


try:
    model = joblib.load(MODELS_DIR / 'model.pkl')
    vectorizer = joblib.load(MODELS_DIR / 'vectorizer.pkl')
except FileNotFoundError as e:
    raise RuntimeError("Model files not found. Run model.py or grid_search.py first to train and save the model.") from e

app = FastAPI(title='sms fraud detection api')

# request schema defines what incoming request body should look like. 
class SMSRequest(BaseModel):
    message: str

@app.get("/")
def root():
    return{"status": "The endpoint is running"}
    
@app.post("/classify")
def classify_sms(request: SMSRequest):  # incoming data must match smsrequest schema define above
    # takes the incoming message and converts it to the TF-IDF numbers using the saved vectorizer
    message_vec = vectorizer.transform([request.message])

    # take the vectorized message from above and run it through the model
    # returns either 0 (ham) or 1 (spam)
    prediction = model.predict(message_vec)[0] # returns a list so [0] grabs the first result

    # Return probability score for each class (ham, spam) that together add to 1.0
    probability = model.predict_proba(message_vec)[0]

    # Return block that returns the input message, whatever the model decided it is, and the max of the two values rounded to 2 decimal places
    return {
        "message": request.message,
        "prediction": "spam" if prediction == 1 else "ham",
        "confidence": round(float(max(probability)) * 100, 2)
    }
    